### ISSUE TITLE
Error: Cannot read property 'setExclude' of undefined

### ISSUE THREAD

**Issue by zizther** [JPeer264/gulp-rcs#11]
I am running RCS on my production build, on testing I am running into an error.
It says `TypeError: Cannot read property 'setExclude' of undefined`

I have tried to add the excludes options along with mapping option, but the error still shows.

I have made sure that no compression or uglification has been done on the CSS, JS or templates (I am using twig files)

I am using gulp v4.0.2

**Comment by JPeer264** [comment]
Hey thanks for your issue. Have you installed the peer-dependencies? 

```sh
npm I rcs-core@2.6.3
```

I think, it is better to mention that in the README as well :)

**Comment by zizther** [comment]
Thanks for getting back.
I did install that as well, but I used `npm i rcs-core`, which i presume installed another version.

I have run the install version you mentioned, and it has worked.

Appreciate your help.

**Comment by JPeer264** [comment]
Alright thanks for your update, I will include that in the README and will also update to the latest rcs-core as it will fix a lot of issues
