### ISSUE TITLE
[FEATURE] Vue / Alpine Conditional Classes

### ISSUE THREAD

**Issue by Chazza** [JPeer264/gulp-rcs#14]
Hey,

Currently RCS ignores classes found within a conditional class.
```js
:class="{ 'pointer-events-auto opacity-100': open }"
```

Thank you!

**Comment by Chazza** [comment]
@JPeer264 what kind of ETA do you think for this? I know you're probably quiet at the moment

**Comment by JPeer264** [comment]
I will look into that today afternoon probably. But in the meantime you could ignore those selectors totally.

At the beginning of your gulpfile you could add this:

```js
const rcsCore = require('rcs-core');

rcsCore.baseLibrary.setExclude(['pointer-events-auto', 'opacity-100']);


// your gulp stuff
```

**Comment by Chazza** [comment]
> 
> 
> I will look into that today afternoon probably. But in the meantime you could ignore those selectors totally.
> 
> At the beginning of your gulpfile you could add this:
> 
> ```js
> const rcsCore = require('rcs-core');
> 
> rcsCore.baseLibrary.setExclude(['pointer-events-auto', 'opacity-100']);
> 
> 
> // your gulp stuff
> ```

Thank you, will this replace these inline with the other classes?

**Comment by JPeer264** [comment]
I am sorry I think I don't fully understood this question. But this line will ignore every selector which is spelled like that (if you meant that).

ref: https://github.com/JPeer264/node-rcs-core/blob/v2.6.3/docs/api/baselibrary.md#setexclude

**Comment by Chazza** [comment]
> 
> 
> I am sorry I think I don't fully understood this question. But this line will ignore every selector which is spelled like that (if you meant that).
> 
> ref: https://github.com/JPeer264/node-rcs-core/blob/v2.6.3/docs/api/baselibrary.md#setexclude

Oh right, I'm looking to replace the classes inside the conditional as well

**Comment by Chazza** [comment]
Currently the issue I face is that the conditional classes aren't replaced, meaning when mobile nav is clicked nothing happens as technically the class no longer exists. I'd like to ideally replace this class as well.

**Comment by JPeer264** [comment]
But `rcs` should ignore this class totally, which means it will also not rename the class in css nor html. Maybe `purgeCss` is removing this class? `rcs` is not removing any class at all, it will just rename them, based on the given css.

**Comment by Chazza** [comment]
> 
> 
> But `rcs` should ignore this class totally, which means it will also not rename the class in css nor html. Maybe `purgeCss` is removing this class? `rcs` is not removing any class at all, it will just rename them, based on the given css.

It's defo RCS, just looked further it runs fine without RCS and the classes remain. When RCS is added, it replaces the class within the stylesheet but not in the conditional class.

**Comment by JPeer264** [comment]
Ok, but the `setExclude` did not work for now?

**Comment by Chazza** [comment]
Yeah didn't do anything

**Comment by JPeer264** [comment]
Alright, I will give you an update tonight ;)

**Comment by Chazza** [comment]
> 
> 
> Alright, I will give you an update tonight ;)

Thank you so much!

**Comment by JPeer264** [comment]
@Chazza could you please retry with `gulp-rcs@3.0.0` and `rcs-core@3.5.0`? This should solve your issue, if not - ping me again please :)

**Comment by entity** [comment]
Wow, works perfectly! Thank you so much 👍

**Comment by JPeer264** [comment]
Glad to hear that :)

**Comment by JPeer264** [comment]
@Chazza I have a question. I saw that https://analyse.org/ is using `rcs` (at least I guess so). Would it be alright that I am mentioning it in [here](https://github.com/JPeer264/node-rcs-core#what-does-it-do)?

**Comment by entity** [comment]
> @Chazza I have a question. I saw that https://analyse.org/ is using `rcs` (at least I guess so). Would it be alright that I am mentioning it in [here](https://github.com/JPeer264/node-rcs-core#what-does-it-do)?

Hey, you certainly can! If you've got Discord, feel free to add me Chazza#0001 happy to talk more.

Analyse is my own brand, but we use RCS and I'm happy to have the site linked 😃

 I'm hoping to swap out more of my sites for RCS in the future, it's setup now (on push) to auto optimise / minify images, purge CSS, RCS, flatten HTML etc.

Thanks so much for your gulp help, still new to it so do appreciate it a lot! Will do that donation on Thursday (when I get paid)

**Comment by JPeer264** [comment]
Alright thanks. Unfortunately I have no discord, but I might get it at some point and will add you then :) Still I'm always up for some chats ;)

**Comment by entity** [comment]
> Alright thanks. Unfortunately I have no discord, but I might get it at some point and will add you then :) Still I'm always up for some chats ;)

Awesome! Anywhere else you use?

**Comment by JPeer264** [comment]
I think I'm pretty old school if it is about that 😅 But usually I use LinkedIn and common SocialMedia :)

**Comment by entity** [comment]
> I think I'm pretty old school if it is about that 😅 But usually I use LinkedIn and common SocialMedia :) 

Follow me then haha, @ChazzaDev on Twitter
