### ISSUE TITLE
Keyframes support

### ISSUE THREAD

**Issue by klimashkin** [JPeer264/gulp-rcs#3]
Seems like it doesn't touch `@keyframes` for now, but would be great to have it changed as well

**Comment by JPeer264** [comment]
@klimashkin I moved it to https://github.com/JPeer264/node-rcs-core/issues/10

**Comment by JPeer264** [comment]
@klimashkin in v`1.1.0` you can now rename keyframes as following:

```js
...
    .pipe(rcs({
        replaceKeyframes: true
    }))
...
```
