### ISSUE TITLE
Couple of issues

### ISSUE THREAD

**Issue by surjithctly** [JPeer264/gulp-rcs#4]
Hello,

Is this still maintained? Got couple of issues. 

~Surjith

**Comment by JPeer264** [comment]
Hey, sure this is still maintained. Which issues do you run into? I might have to update `rcs-core` which will might fix couple of issues.

**Comment by surjithctly** [comment]
1. Some of the classes are not converting causing page to display like broken
2. Hex color is taking as id and converting it as well. eg: #ffbccd to #qa

**Comment by JPeer264** [comment]
Please update to `gulp-rcs@2.0.0`. If you still have troubles, please open a new issue with detailed error logs.
