### ISSUE TITLE
tag[paramName="paramvalue"] problem

### ISSUE THREAD

**Issue by c00lib1n** [JPeer264/gulp-rcs#6]
String like as:
`.tabsIconed .tabs__nav a[href="#tabs_availability"]:before {...}`

after .pipe(rcs())  convert to 

`.ja .jo a[href="#jf:before {...}`

Missing closing ] and " char.

**Comment by JPeer264** [comment]
hey thanks for your issue. I'm gonna update `rcs-core`. This may be resolved by then :)

**Comment by JPeer264** [comment]
Should be fixed in v`2.0.1`
